config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'
  post 'messages/create_video'
  resources :messages do
    member do
      post 'update_video'
    end
  end
  get 'messages/category/:category_id/' => "messages#index" , as: :new_message_category
  resources :categories do 
    member do
      get 'index', as: :category_show
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base

belongs_to :category

has_attached_file :video, :path => ":rails_root/public:url",
						  :url => "/system/:class/:attachment/:id/:style/:basename.:extension",
						  :default_url => "/videos/original/example.webm"

validates_attachment_content_type :video, :content_type => ['application/x-matroska',"audio/mp4", "video/mp4", "video/webm", 'application/octet-stream']

PARENTS = [1,2,3,4]

# def message_not_blank_when_submitted
#   if body.empty? && !video?
#     errors.add(:body, 'must not be blank upon submit')
#   end
# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
		@category = params["id"].present? ? Category.find(params["id"]) : Category.first
		@messages = @category.messages.where(parent_id: nil)

	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	
	skip_before_action :verify_authenticity_token, only: [:update_video]

	def index
		@parents = Message::PARENTS
		@message = Message.all.order("created_at DESC")

		@category_id = params["category_id"]
		if @category_id
			@message_parent = Category.find(@category_id).messages.where(parent_id:nil).last
			@messages = Category.find(@category_id).messages.where(parent_id:@message_parent.id).order("created_at DESC")
		end
	end

	def create_video
		@message = Message.new(message_params)
    if @message.save
    	render json: {success: true, message_id: @message.id}
    else
    	render json: {success: false}
    end
	end

	def update_video
		@message = Message.find(params["id"])
    if @message.update(message_params)
      redirect_to new_message_category_path(params["message"]["category_id"])
    else
      redirect_to root_url
    end
	end

	def message_params
	  params.require(:message).permit(:title, :description, :parent_id, :category_id, :video)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def content_type(video)
		vid = video.instance.video_file_name unless video.instance.blank?

		content_type = if vid.blank?
			'webm'
		else
			vid.split('.').last
		end
	end
end

app/views/categories/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3">
			<div class="well well-lg">
				<h4>Programs</h4>
				<% @categories.each do |category| %>
				<ul class="list-group">
					<li class="list-group-item"> <%= link_to category.name, category_show_category_path(category) %></li>
				</ul>
				<%end%>
			</div>
		</div>
		<div class="col-md-6">
			<div class="well well-lg">
				<h4>List of Programs</h4>
				<% if @messages.present? %>
					<% @messages.each do |msg| %>
					<ul class="list-group">
						<li class="list-group-item"> <%= link_to msg.title, new_message_category_path(msg.category_id), 'data-no-turbolink' => true %></li>
					</ul>
					<%end%>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoMessaging</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
  
  <%= javascript_include_tag 'application'%>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <%= csrf_meta_tags %>

  <!-- <link rel="stylesheet" href="http://assets-cdn.ziggeo.com/v1-stable/ziggeo.css" />
  <script src="http://assets-cdn.ziggeo.com/v1-stable/ziggeo.js"></script>
  <script>ZiggeoApi.token = '<%#= ENV['ZIGGEO_KEY'] %>';</script> -->

  <!-- <link href="//vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet">
  <script src="//vjs.zencdn.net/5.19/video.min.js"></script> -->
  
  <!-- Purejs/videorecorderjs -->
<!--   <link href="http://vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/5.19/video.min.js"></script>
  <script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script> -->


  <!-- clipchimp  -->
  <!-- <script type= "text/javascript" src= "https://api.clipchamp.com/dbmtY6gGGRrXVjzAUrZwt6vNTLE/button.js"></script>
  <script type="text/javascript">
  clipchamp.preload();
  </script> -->

</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/backup.html.erb
<div class="container">
  <div class="row">
  <div class="well well-lg">
  <div class="clear-fix"></div>
    <div class="col-md-12">
        <div class="">
         <video width="320" height="240" controls>
             <source src="<%= @message_parent.video %>" type="video/webm">
             Your browser does not support the video tag.
           </video>
        
          <h3><%= @message_parent.title %></h3>
          <div><p> <%= @message_parent.description %></p></div>
        </div>

      <% if @messages %>
        <% @messages.each do |message| %>
        <div class="">
           <video width="320" height="240" controls>
             <source src="<%= message.video %>" type="video/webm">
             Your browser does not support the video tag.
           </video>
        
          <h3><%= message.title %></h3>
          <div><p> <%= message.description %></p></div>
        </div>
        <% end %>
      <% end %>
    </div>

  <br>
  <div class="row">
      <div class="col-md-6">
        <video id="myVideo" class="video-js vjs-default-skin"></video>
        <input id="fileupload" type="file" name="message[video]" class="hide" multiple>
      </div>
  </div>
  
  <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <select id="category_id" class="form-control">
          <%= @categories.each do |cat|%>
            <option value="<%= cat.id %>"><%= cat.name %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group">
          <select id="parent_id" class="form-control">
          <%= @parents.each do |prn|%>
            <option value="<%= prn %>"><%= prn %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group">
          <input type="text" id="title" placeholder="title" class="form-control" >
        </div>
        <div class="form-group">
          <input type="text" id="description" placeholder="description" class="form-control">
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(function() {
  // Initialize the jQuery File Upload widget
  $('#fileupload').fileupload({
    url: '/messages/create_video',
    formData: { "message[title]": $("#title").val(),
                "message[description]": $("#description").val() },
                "message[parent_id]": $("#parent_id").val(),
                "message[category_id]": $("#category_id").val(),
    // data: {parent_id: 1},
    done: function(e, data) {
      $.each(data.files, function(index, file) {
        var message = 'Upload complete: ' + file.name + ' (' +
          file.size + ' bytes)';
        $('<p/>').text(message).appendTo(document.body);
        console.log(message);
      });
    }
  });

  // setup videojs-record
  var player = videojs("myVideo",
    {
        controls: true,
        width: 320,
        height: 240,
        controlBar: {
            volumeMenuButton: false
        },
        plugins: {
            record: {
                audio: false,
                video: true,
                maxLength: 5,
                debug: true
            }
        }
    });

  // player error handling

  player.on('deviceError', function() {
    console.warn('device error:', player.deviceErrorCode);
  });
  player.on('error', function(error) {
    console.log('error:', error);
  });


  // data is available
  player.on('finishRecord', function() {
    // the blob object contains the audio data
    var videoFile = player.recordedData;

    // upload data to server
    var filesList = [videoFile];
    // param = {message:[{video:""}]}
    // $('#fileupload').fileupload('add', { param["message"][0]["video"]: filesList });
    // $('#fileupload').fileupload('add', { files: filesList });


    $('#fileupload').fileupload('add', {files: filesList});
    console.log(filesList);
    // setTimeout(function() {
    //   $.ajax({
    //     url: '/messages/create_video',
    //     method: "POST",
    //     data: { 'videos_blob': $(player.el_).find('video').attr('src')}
    //   });
    // }, 100);
    // console.log($('#fileupload').val())

    });


});
</script>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
    <div class="well well-lg">
      <div class="col-md-12">
        <div class="">
          <video width="320" height="240" controls>
            <source src="<%= @message_parent.video %>" type="video/webm">
             Your browser does not support the video tag.
          </video>
        
          <h3><%= @message_parent.title %></h3>
          <div><p> <%= @message_parent.description %></p></div>
        </div>
        <hr>
        <br>

        <% if @messages %>
          <% @messages.each do |message| %>
          <div class="">
              <video width="320" height="240" controls>
               <source src="<%= message.video %>" type="video/<%= content_type(message.video) %>">
               Your browser does not support the video tag.
              </video>
              <br>
            <div><p style="margin-top: 10px;"> <%= message.description %></p></div>
          </div>
          <hr>
          <br>
          <% end %>
        <% end %>
      </div>

      <div class="row">
        <div class="col-md-6">
          <video id="myVideo" class="video-js vjs-default-skin" controls></video>
          <input id="fileupload" type="file" name="message[video]" class="hide" multiple>
            <p style="margin-top: 10px;">
              <%= link_to "Record", "#", id:"record", class:"btn btn-primary", onclick: "recordVideo();return false;" %> | 
              <%= link_to "Pause", "#", id:"pause", class:"btn btn-primary", onclick: "pauseVideo();return false;" %> | 
              <%= link_to "Resume", "#", id:"resume", class:"btn btn-primary", onclick: "resumeVideo();return false;" %> |            
              <%= link_to "Stop", "#", id:"stop", class:"btn btn-primary", onclick: "stopVideo();return false;" %> | 
              <%= link_to "Reset", "#", id:"reset", class:"btn btn-primary", onclick: "resetVideo();return false;" %> |
            </p>
        </div>
      </div>
    
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
          <form method="post" id="update_video" >
            <input type="text" name="message[parent_id]" id="parent_id-x" value="<%= @message_parent.id %>" placeholder="title" class="form-control hide" >
            <input type="text" name="message[category_id]" id="category_id-x" value="<%= @category_id %>" placeholder="title" class="form-control hide" >
            <input type="text" name="message[description]" id="description-x" placeholder="description" data-val="" class="form-control">
          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>  
  var player = videojs("myVideo",
      {
        controls: true,
        width: 320,
        height: 240,
        controlBar: {
          volumeMenuButton: false
        },
        plugins: {
          record: {
            audio: false,
            video: true,
            maxLength: 50,
            videoMimeType: 'video/mp4',
            debug: true,
            videoRecorderType: 'auto'
          }
        }
      });
    
  function recordVideo(){
    // getVal();
    countdownTimer();

    setTimeout(function(){ player.recorder.start(); }, 3000);
  }

  function getVal(){
    $("#description").data("val", $("#description").val())
  }
  
  function pauseVideo(){
    player.recorder.pause();
  }
  
  function stopVideo(){
    player.recorder.stop();
  }
  
  function resetVideo(){
    player.recorder.reset();
    player.recorder.getDevice();
  }

  function resumeVideo(){
    player.recorder.resume();
  }
  
  function countdownTimer(){
    var timeleft = 3;
    $('.vjs-record p').text(timeleft);
    
    var downloadTimer = setInterval(function(){
      timeleft--;
      $('.vjs-record p').text(timeleft);
      console.log(timeleft);
      if(timeleft <= 0){
          clearInterval(downloadTimer);
        $('.vjs-record p').text("");
      }
    },1000);
  }
  
  // function callPlayer(){
//    // setup videojs-record
//    return
//  }
  
$(document).ready(function() {

  $('#fileupload').fileupload({
    url: '/messages/create_video',

    done: function(e, data) {
      console.log(data.result);
      if (data.result.success == true) {
        $("#update_video").prop('action', '/messages/'+data.result.message_id+'/update_video').submit();
        console.log(data.result.message_id);
      }else{
        alert("error created video")
      }
    }
  });
  
  // var player = callPlayer();
  
  // player error handling

  player.on('deviceError', function() {
    console.warn('device error:', player.deviceErrorCode);
  });
  
  player.on('deviceReady', function(){
    $('div.vjs-record-button.vjs-control.vjs-icon-record-start').hide();
    $('.vjs-record').append("<p class='countdown_timer'></p>");
  });
  
  player.on('error', function(error) {
    console.log('error:', error);
  });

  player.on('startRecord', function(){
    console.log('started recording!');
  });

  player.on('stopRecord', function(){
    console.log('pause recording!');
  });

  player.recorder.getDevice();
  
  // data is available
  player.on('finishRecord', function() {
    // the blob object contains the audio data
    var videoFile = player.recordedData;

    console.log("Player Object = ", $(player.el_).find('video').attr('src'));

    console.log('finished recording: ', videoFile);

    // upload data to server
    var filesList = [videoFile];
    $('#fileupload').fileupload('add', {files: filesList});
    console.log(filesList);
  });

});
</script>

app/views/messages/new.html.erb
<style>
	.countdown_timer{
		font-size: 60px;
		    text-align: center;
		    position: absolute;
		    width: 100%;
		    margin: 0px;
		    top: 35%;
	}
	</style>

<video id="myVideo" class="video-js vjs-default-skin"></video>
<%#= form_for @message do |f| %>
  <%#= f.text_field :description  %>
  <%#= f.text_field :title  %>
  <%#= f.file_field :video, id: "fileupload", multiple:true %>
<%# end %>
<!-- <form> -->
  <!-- <input type="text">
  <input type="text"> -->

  <input id="fileupload" type="file" name="message[video]" multiple>
<!-- </form> -->
<p>
	<%= link_to "Record", "#", onclick: "recordVideo();return false;" %> | 
	<%= link_to "Pause", "#", onclick: "pauseVideo();return false;" %> | 
	<%= link_to "Stop", "#", onclick: "stopVideo();return false;" %> | 
	<%= link_to "Reset", "#", onclick: "resetVideo();return false;" %>
	
</p>


<% if @messages %>
  <% @messages.each do |message| %>
    <div><%= message.video %></div>
	<video width="320" height="240" controls>
	  <source src="<%= message.video %>" type="video/webm">
	Your browser does not support the video tag.
	</video>
	
    <div><%= message.title %></div>
    <div><%#= message.parent_id %></div>
  <% end %>
<% end %>

<script>	
	var player = videojs("myVideo",
	    {
	        controls: true,
	        width: 320,
	        height: 240,
	        controlBar: {
	            volumeMenuButton: false
	        },
	        plugins: {
	            record: {
	                audio: false,
	                video: true,
	                maxLength: 50,
	                debug: true
	            }
	        }
	    });
		
	function recordVideo(){
		countdownTimer();
		setTimeout(function(){ player.recorder.start(); }, 3000);
	}
	
	function pauseVideo(){
		player.recorder.pause();
	}
	
	function stopVideo(){
		player.recorder.stop();
	}
	
	function resetVideo(){
		player.recorder.reset();
		player.recorder.getDevice();
	}
	
	function countdownTimer(){
	    var timeleft = 3;
		$('.vjs-record p').text(timeleft);
	    var downloadTimer = setInterval(function(){
	    timeleft--;
		$('.vjs-record p').text(timeleft);
		console.log(timeleft);
	    if(timeleft <= 0){
	        clearInterval(downloadTimer);
		    $('.vjs-record p').text("");
		  }
	    },1000);
		
	}
	
	// function callPlayer(){
// 	  // setup videojs-record
// 	  return
// 	}
	
$(function() {
  // Initialize the jQuery File Upload widget
  $('#fileupload').fileupload({
    url: '/messages/create_video',
    done: function(e, data) {
      $.each(data.files, function(index, file) {
        var message = 'Upload complete: ' + file.name + ' (' +
          file.size + ' bytes)';
        $('<p/>').text(message).appendTo(document.body);
        console.log(message);
      });
    }
  });
  
  
  
  // var player = callPlayer();
	
  // player error handling

  player.on('deviceError', function() {
    console.warn('device error:', player.deviceErrorCode);
  });
  
  player.on('deviceReady', function(){
  	$('div.vjs-record-button.vjs-control.vjs-icon-record-start').hide();
	$('.vjs-record').append("<p class='countdown_timer'></p>");
  });
  
  player.on('error', function(error) {
    console.log('error:', error);
  });
  
  player.recorder.getDevice();
  
  // data is available
  player.on('finishRecord', function() {
    // the blob object contains the audio data
    var videoFile = player.recordedData;

    console.log("Player Object = ", $(player.el_).find('video').attr('src'));

    console.log('finished recording: ', videoFile);

    // upload data to server
    var filesList = [videoFile];
    // param = {message:[{video:""}]}
    // $('#fileupload').fileupload('add', { param["message"][0]["video"]: filesList });
    // $('#fileupload').fileupload('add', { files: filesList });


    $('#fileupload').fileupload('add', {files: filesList});
    console.log(filesList);
    // setTimeout(function() {
    //   $.ajax({
    //     url: '/messages/create_video',
    //     method: "POST",
    //     data: { 'videos_blob': $(player.el_).find('video').attr('src')}
    //   });
    // }, 100);
    // console.log($('#fileupload').val())

    });


});
</script>